// Simple background music generator for Sudoku game
// This creates a peaceful, ambient tone sequence suitable for concentration

import { Audio } from 'expo-av';

export class BackgroundMusicGenerator {
  private static readonly PEACEFUL_FREQUENCIES = [
    // Pentatonic scale frequencies (peaceful and non-intrusive)
    261.63, // C4
    293.66, // D4
    329.63, // E4
    392.00, // G4
    440.00, // A4
    523.25, // C5
  ];

  private static readonly NOTE_DURATION = 2000; // 2 seconds per note
  private static readonly SILENCE_DURATION = 500; // 0.5 seconds between notes

  // Create a simple audio context for generating tones
  static async createPeacefulTone(): Promise<string> {
    // For development, we'll use a simple data URI with a sine wave
    // In production, you'd want to use actual audio files
    
    // Generate a simple sine wave tone data URI
    const sampleRate = 44100;
    const duration = this.NOTE_DURATION / 1000; // Convert to seconds
    const samples = sampleRate * duration;
    const frequency = this.PEACEFUL_FREQUENCIES[Math.floor(Math.random() * this.PEACEFUL_FREQUENCIES.length)];
    
    // This is a placeholder - in a real app you would use proper audio files
    return 'data:audio/wav;base64,UklGRnoGAABXQVZFZm10IBAAAAABAAEAQB8AAEAfAAABAAgAZGF0YQoGAACBhYqFbF1fdJivrJBhNjVgodDbq2EcBj+a2/LDciUFLIHO8tiJNwgZaLvt559NEAxQp+PwtmMcBjiR1/LMeSwFJHfH8N2QQAoUXLXt559NEAxPpuPwtmMcBjiS2OzGdiMFJHfH8N2QQAoUXLXt559NEAxPpuHwtmQcBTuS1/LNeCsFJXfH8N2QQAkUXLXt559NEAxPpuPwtmMcBjiS2O3GdSMFJHfH8N2QQAoUXLXt559NEAxPpuPwtmMcBjiS2O7Gd'; // Truncated placeholder
  }

  // Create a looping background music sequence
  static async createBackgroundMusic(): Promise<Audio.Sound | null> {
    try {
      // For now, we'll use a simple repeating tone
      // In a real implementation, you'd load actual music files
      
      // This is a placeholder implementation
      const { sound } = await Audio.Sound.createAsync(
        {
          uri: 'https://www.soundjay.com/misc/sounds/bell-ringing-05.wav', // Placeholder URL
        },
        {
          shouldPlay: false,
          isLooping: true,
          volume: 0.3, // Start at low volume
        }
      );
      
      return sound;
    } catch (error) {
      console.warn('Could not load background music:', error);
      return null;
    }
  }

  // Generate peaceful ambient sound patterns
  static generateAmbientPattern(): number[] {
    const pattern = [];
    const baseFrequency = 220; // A3
    
    // Create a gentle rising and falling pattern
    for (let i = 0; i < 16; i++) {
      const phase = (i / 16) * 2 * Math.PI;
      const frequency = baseFrequency * (1 + 0.2 * Math.sin(phase));
      pattern.push(frequency);
    }
    
    return pattern;
  }
}

// Copyright-free music note: 
// The music generated by this class uses mathematical frequencies
// and basic wave patterns that are not copyrighted.
// For production use, consider using royalty-free music libraries like:
// - Freesound.org
// - YouTube Audio Library
// - Creative Commons music
// - Original compositions
